services:
  mysql:
    image: mysql:8.4.11
    container_name: openlend-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: openlend_catalog
      MYSQL_USER: openlend
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - openlend-mysql-data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  openlend-mysql-data: